### ISSUE TITLE
Change the way the season is returned in Series models.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#111]
From the docs:

> 164
> First 2 numbers are the year (16 is 2016). Last number is the season starting at 1 (3 is Summer).

This just seems.... Extremely odd to me. Parsing this into something meaningful requires extra work, and it's just strange overall.

I'm genuinely curious, why was this chosen to return season information for a series?

Wouldn't returning a dictionary like this instead of a weird number make much more sense?:

```JSON
season: {
    "year:" 2016
     "season": "summer"
}
```

I personally have no problems parsing this into something meaningful, but what happens to the series released before 2000's, and *what if* Anilist stays long enough to overflow the first two digits into a 00?

**Comment by joshstar** [comment]
Its a code format we've been using since the first days of anichart, I don't really remember why I chose to do it that way but it works fine for the most part. I never really thought about changing its return value to something more readable, just something I forgot about. Anime seasons weren't really a thing pre-2000 so it doubt that would really be an issue.

As this is a stable api I can't really change a data format like that so it will have to be something for v2.

I'll close this for now but add it to my v2 notes.
