### ISSUE TITLE
[Feature] More specific episode info

### ISSUE THREAD

**Issue by belldandu** [joshstar/AniList-API-Docs#128]
Like what characters were seen in the episode, what their role was in the episode, the episode title (english, romaji, japanese) and or alts, the episode summary or synopsis, etc.

**Comment by joshstar** [comment]
This is more of a data issue, at the moment we don't really have the community/staff to support our current data set so adding stuff like this isn't something we can really do at the moment. There are plans to get episode information for streaming sites (crunchyroll, funimation etc) so that will provide some data such as images, titles, and episode descriptions but no eta for when that will be implemented.
