### ISSUE TITLE
Is there any way to get the total of series item？

### ISSUE THREAD

**Issue by ssshooter** [joshstar/AniList-API-Docs#152]
or get a random item like Random article of wikipedia?

**Comment by Kazakuri** [comment]
The closest you can get is using the [browse](anilist-api.readthedocs.io/en/latest/series.html#browse) endpoint and sorting by "id-desc" to get the newest anime/manga ID.
But note that the newest ID does not at all reflect the count of series at all since many IDs have been skipped.

It is possible to generate a random ID using the newest ID as an upper limit then requesting that ID, but you would likely have to end up making a couple requests if you wanted to put constraints on the returned series or to make sure that it's valid.

Though fetching a random series within a certain set of restraints does sound like a good inclusion into V2 of the API. Feel free to make an issue about it [here](https://github.com/AniList/ApiV2-GraphQL-Docs/issues) to discuss it further.

**Comment by ssshooter** [comment]
@Kazakuri Thanks a lot !
