### ISSUE TITLE
Issue access token

### ISSUE THREAD

**Issue by BodoqueZorrilla** [joshstar/AniList-API-Docs#153]
Hi i'm trying to enable my access_token with this:

https://anilist.co/api/auth/access_token?grant_type=authorization_code&client_id=bodoquezorrilla-j8uf6&client_secret=<client_secret\>&redirect_uri=&code=\<code\>

And have this result:
{"error":{"status":404,"messages":["API route not found."]}}

Am I doing correct this? Or Why is this happening?

**Comment by Kazakuri** [comment]
Hey there, it looks like you're probably doing a GET request to that URL, according to the [docs for the authorization code grant](http://anilist-api.readthedocs.io/en/latest/authentication.html#grant-authorization-code) you should be doing a POST request.

Also, I edited the authorization code and your client secret from your comment because you are required to keep your client_secret a well, secret, and an authorization code could be used to compromise your account if it fell into the wrong hands.

**Comment by BodoqueZorrilla** [comment]
Hi again, 
Thanks for your reply, now i'm doing with Postman REST-Client sending with POST request and I got this answer:
 "error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"code\" parameter.".

Can you help me?.

**Comment by Kazakuri** [comment]
My guess is that the auth code you were using ended up expiring and became invalid. Can you try again with a fresh auth code?

**Comment by BodoqueZorrilla** [comment]
Thanks, I resolved with your advise.

Regards
