### ISSUE TITLE
Add access_token header and return 403 error

### ISSUE THREAD

**Issue by ssshooter** [joshstar/AniList-API-Docs#154]
but url parameter is OK

![image](https://user-images.githubusercontent.com/13051472/29747697-1d63d172-8b35-11e7-87d5-87355ef7df09.png)
![image](https://user-images.githubusercontent.com/13051472/29747703-413f3780-8b35-11e7-86dd-1b69aa9ed1c5.png)

**Comment by Kazakuri** [comment]
From the [docs page](http://anilist-api.readthedocs.io/en/latest/authentication.html):

```
Now to access the resource server on the resource owner’s behalf, simply include the following header with all your requests

Authorization: Bearer access_token
```

From the request it looks like you're including the wrong header.

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/29773472-42de232a-8c30-11e7-98aa-f140b1bd89ad.png)
![image](https://user-images.githubusercontent.com/13051472/29773485-4f1b0040-8c30-11e7-92f2-b4576cab0263.png)
emmmm...fail with axios...

**Comment by Kazakuri** [comment]
Judging by the error at the bottom of the first screenshot, it looks like it's failing because of a CORS error because AniList doesn't provide an appropriate `Access-Control-Allow-Origin` header.

There's a pretty good Stack Overflow [answer here](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe) that goes into more details about CORS and how to get around it.

**Comment by ssshooter** [comment]
:sob: ok , I prefer to use url parameter rather than proxy, thanks for your guidance !
