### ISSUE TITLE
Mind sharing a little bit about the technical aspect of hosting anilist?

### ISSUE THREAD

**Issue by mrahhal** [joshstar/AniList-API-Docs#82]
I'm just inquiring if you don't mind me asking, I'd like to know how much I have to put into hosting providers, database providers and other technical stuff in order to run a site as big as anilist. How much does it approx cost, do you use shared or dedicated hosting, that stuff...

Although I'm a bit on the microsoft stack side, it doesn't matter. So, if you don't mind sharing.

**Comment by joshstar** [comment]
Sorry for the late reply, was traveling.
In terms of software our stack is pretty much as ordinary as you could get for the web; Nginx, PHP 5.6 (hopefully 7 soon) with laravel, MySql, memcached etc. Not exactly the fastest or most efficient stack there is but its easy to work with and allows me to get things done and iterate quickly. (that is when I'm not refactoring the code base for the 4th time, this time is the last time I swear :S)

As for hardware we currently have our own private server, its really very old at this point though. The CPU is getting up to 8 years old now but pretty much everything in the system has been upgraded and is _some what_ modern in comparison. 64gb of ram, couple ssds and hard drives in raid, can't remember the exact CPU but its an intel 6 core at least. We run various VMs (mostly debian but probably moving to Ubuntu soon) to handle different things and host a few other unrelated little sites for ourselves or the odd client. We have pretty much everything go via cloudflare now, its pretty great really, at least for saving bandwidth, gone through 16TB in the last month and cloudflare saved about 13 of that.

We did run on shared hosting for a little while back in early 2013 but were very quickly kicked off for using too many resources. 
We should be moving to a rented dedicated server very soon which will be a nice change and not too much difference in terms of price compared to the server rack space rental.

We have some outside funding (for the time being anyway) so it doesn't cost us the full amount but it would cost upwards of £200/m. The outside funding is very much dependent purely on the generosity of the 3rd party, they don't really get anything out it, when that runs out though we'll probably need to look for additional funding through donations or other means as I don't really like running ads very much.

Considering the age of our server, you could probably run something the size of AniList and AniChart on something like the $160 digital ocean package without too much of a problem, but the pricing on cloud services is rather high so you could probably get a better deal elsewhere. I wouldn't really recommend going for something big straight away though as its taken anilist and anichart ages to get to where it is an we're still very much a small site really. I would say to start with something small a scale vertically when needed.

**Comment by mrahhal** [comment]
Me and you both regarding refactoring whole code bases haha. And yes, no matter how large you're planning your site to be one should always start small and scale as needed.

This was very interesting, thank you very much and good work on anilist! I personally find it the best tracker there is. Hoping to see anilist open sourced soon to start contributing.

(I'm not closing this as people might find this interesting, but feel free to do that)

**Comment by soruly** [comment]
How large is the anilist team? on developing software and handling servers?

**Comment by joshstar** [comment]
Pretty much just me on the dev side of things. We have another guy who helps out with server stuff sometimes, he can also physically drive to the server if we need to do an upgrade or something serious breaks too.

We have about 17 mods that help out with the site data and community, their all great though a fair few of them (and I'm sure their aware) don't really do anything anymore and either just hang around or have dropped out of contact, which is a shame.

I do get asked a fair bit by random devs on twitter or elsewhere if I'd like them to help out with the dev work. But we have quite an application process just to be become a mod, and I don't think just saying yes or getting applications from random devs I've never really conversed with will get us a dev who shares the same kind of ideas or visions for the direction of the site. Or has different ideas as to their position of ownership now they're a dev.

Which is why I'm very much looking forward to open sourcing and then expanding the dev team. Open sources allow some dev to make the odd little pr (which is still great) but some will dedicate more time and effort (I hope anyway), and overtime I'll be able to really see if they have the same kind of ideas (or even better ideas) as for what we should do with the site, and then invite them to be apart of the dev team.

**Comment by mrahhal** [comment]
It's all understandable I'm sure. And now that you mention it, I guess open sourcing this has even more meaning/benefits than I first thought.

**Comment by miguemely** [comment]
@joshstar Why not something like OVH/SoYouStart?

**Comment by joshstar** [comment]
Our funding was related to the specific server we're currently using but thats no longer the case so we are moving to a similar service as those soon.
