### ISSUE TITLE
Oauth accestoken not returning

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#84]
A lot of AL users have Oauth issues.

According the app:
07-02 04:07:58.714 I/Atarashii(11844): AccountService: The accestoken will expire in -29047 minutes.
07-02 04:07:59.444 E/Atarashii(11844): ALApi.getAccesToken(): Attempt to read from field 'java.lang.String net.somethingdreadful.MAL.api.ALModels.OAuth.access_token' on a null object reference

You will see that the acces token is expired and the app request the new token.
In the line below you will see that AL does not return the token for some reason.
Even logging out and logging in does not seem to help.

I created this issue because FujoshiFever made a support ticket and I saw many other users having issues.
This never happened before and I did not published a new release recently.
Is this related to some server issues?

**Comment by Kazakuri** [comment]
> -29047 minutes

About 14 days ago AniList kept going down and a bunch of user's refresh tokens stopped working.
If you checked out the actual response from the API you'd probably see:
```
{
    "error": "invalid_request",
    "error_description": "The refresh token is invalid."
}
```

**Comment by ratan12** [comment]
So it is related to the server issues but if the request tokens are not working they won't be able to use any app :o

@joshstar Do you have some more info?
If it doesn't get fixed soon I have to write a post mentioning that there are some temp issues.

**Comment by Kazakuri** [comment]
What? Just get them to re-authenticate to generate a new authorization pin/code to get a new refresh token.

**Comment by joshstar** [comment]
Due to some issues the server time got set incorrectly, causing the cron job that deletes expired tokens to delete a lot of other oauth tokens & codes due to foreign keys. We don't keep that regular back ups of our oauth data, as it gets rather huge very quickly. I'll look into restoring what I can.

In the mean time the best and only advice I can give is to request your users to re-authorize your app with their anilist accounts, as that should give you all new auth codes and fix the issues. If I can't fix the issue on the database end you may want to release an update that removes the current anilist auth data from the app, forcing the users to re-auth, but hopefully that won't be necessary. 

Apologies for the inconvenience. I wasn't aware the server caused these issues until very recently.

**Comment by ratan12** [comment]
I forgot to mentioned that the user i mentioned before did logged out and logged in again which didn't solved the issue.

That is actually the reason I made this ticket.

**Comment by joshstar** [comment]
I've had feedback that does state that re-authorising does fix the issue, perhaps ask the user to revoke the app via the [anilist settings](http://anilist.co/settings/apps) and then try again?

**Comment by ratan12** [comment]
I hope this does help him or her.
I will you inform on the progress if I get a response.

**Comment by joshstar** [comment]
If it does work I can revoke all your users auths on my end so they won't need to do it manually.

**Comment by ratan12** [comment]
Yes it worked but I think he misunderstood me.
He didn't logged out when he said he did.

Anyway it has been resolved and there is no need to revoke our at your side.
He also said thanks to you ;)

**Comment by joshstar** [comment]
Okay good to hear.

I'll keep this issue open for awhile just in case others are having similar problems.

**Comment by ratan12** [comment]
I see some more cases where a logout was not good enough.
