### ISSUE TITLE
What are the "role" and "relation_type" properties?

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#89]
I can't figure what these two parameters are to represent in Anime and Small Anime models.

**Comment by Kazakuri** [comment]
Did you accidentally the title?

**Comment by AndyIbanez** [comment]
It looks like GitHub is having issues with quotation marks haha.

I'm talking about "role" and "relation_type"

**Comment by AndyIbanez** [comment]
Welp there we go.

**Comment by Kazakuri** [comment]
Oh, this was brought up in a previous issue (#50)

- `relation_type` is for when the anime is in the `relations` array of the `anime/{id}/page` endpoint, it's just a string like "Prequel", "Sequel", "Adaption", etc.
- `role` is always going to be null since it's only used in the `staff` / `characters` array on the `anime/{id}/page` endpoint, and there it's just a string like "Original Story", "Supporting", "Character Design", etc.

**Comment by AndyIbanez** [comment]
Gotcha, thanks.

**Comment by AndyIbanez** [comment]
Is there any way I can get a list of all the supported values for both properties?

**Comment by Kazakuri** [comment]
`relation_type`:
  - `"Prequel"`
  - `"Sequel"`
  - `"Parent"`
  - `"Side Story"`
  - `"Character"`
  - `"Summary"`
  - `"Alternative"`
  - `"Spin off"`
  - `"Other"`
  - `"Adaption"`

`role` can be pretty much anything, since it is just typed in when adding a staff member.

**Comment by AndyIbanez** [comment]
Thanks, very nice list.

**Comment by AndyIbanez** [comment]
Right, one more important thing, you mentioned manually input values.

I'm writing a wrapper for Swift, and I want to use enums for all fields that are not free form.

Is the `language` property of the Staff/Character model free form, or is there a finite set of values?

**Comment by Kazakuri** [comment]
It appears to also be fixed

![http://i.imgur.com/5DPRDMD.png](http://i.imgur.com/5DPRDMD.png)

**Comment by AndyIbanez** [comment]
Another awesome list, thanks. I think that's everything I need for now.
